"""initial schema

Revision ID: 289996a16abd
Revises: 
Create Date: 2026-09-06 10:54:22.626580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '289996a16abd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('user_message', sa.Text(), nullable=True),
    sa.Column('ai_decision', sa.Text(), nullable=True),
    sa.Column('tool_name', sa.String(length=128), nullable=True),
    sa.Column('arguments', sa.JSON(), nullable=True),
    sa.Column('result', sa.Text(), nullable=True),
    sa.Column('execution_time_ms', sa.Float(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_telegram_user_id'), 'audit_logs', ['telegram_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('conversation_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_history_chat_id'), 'conversation_history', ['chat_id'], unique=False)
    op.create_index(op.f('ix_conversation_history_created_at'), 'conversation_history', ['created_at'], unique=False)
    op.create_table('conversation_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('summary_text', sa.Text(), nullable=False),
    sa.Column('covers_up_to_message_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_summaries_chat_id'), 'conversation_summaries', ['chat_id'], unique=False)
    op.create_table('monitoring_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by_telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('rule_type', sa.String(length=64), nullable=False),
    sa.Column('condition', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pending_confirmations',
    sa.Column('action_id', sa.String(length=64), nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=True),
    sa.Column('tool_name', sa.String(length=128), nullable=False),
    sa.Column('arguments', sa.JSON(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('agent_session_snapshot', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('action_id')
    )
    op.create_index(op.f('ix_pending_confirmations_status'), 'pending_confirmations', ['status'], unique=False)
    op.create_index(op.f('ix_pending_confirmations_telegram_user_id'), 'pending_confirmations', ['telegram_user_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('port', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_telegram_user_id'), 'users', ['telegram_user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_telegram_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('settings')
    op.drop_table('projects')
    op.drop_index(op.f('ix_pending_confirmations_telegram_user_id'), table_name='pending_confirmations')
    op.drop_index(op.f('ix_pending_confirmations_status'), table_name='pending_confirmations')
    op.drop_table('pending_confirmations')
    op.drop_table('monitoring_rules')
    op.drop_index(op.f('ix_conversation_summaries_chat_id'), table_name='conversation_summaries')
    op.drop_table('conversation_summaries')
    op.drop_index(op.f('ix_conversation_history_created_at'), table_name='conversation_history')
    op.drop_index(op.f('ix_conversation_history_chat_id'), table_name='conversation_history')
    op.drop_table('conversation_history')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_telegram_user_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
